[package]
name = "net-ssr"
description = "Network Secondary Surveillance Radar"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "interrogator"
path = "src/interrogator.rs"

[[bin]]
name = "transponder"
path = "src/transponder.rs"

[dependencies]
hostname = "^0.4"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.6"
pnet = "0.28.0"
command = { path = "./src/command" }

[build-dependencies]
clap_mangen = "0.2.22"
command = { path = "./src/command" }
