name: Cargo Publish

on:
  workflow_dispatch

jobs:
  crates_io_publish:
    name: Publish (crates.io)
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: cargo login
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}

      - name: "cargo publish"
        run: |-
          cargo publish \
            --no-verify
            --dry-run
