name: Build and Push Docker Images

on:
  release:
    types: [published]

jobs:
  build-and-push:
    strategy:
      matrix:
        binary: [interrogator, transponder]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: libook
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=${VERSION} \
            -t libook/net-ssr-${{ matrix.binary }}:${VERSION} \
            -t libook/net-ssr-${{ matrix.binary }}:latest \
            -f docker/Dockerfile.${{ matrix.binary }} \
            --push \
            .
