name: Build and Push Docker Images

on:
  workflow_dispatch
  # release:
  #   types: [published]

jobs:
  build-and-push:
    strategy:
      matrix:
        binary: [interrogator, transponder]
        include:
          - build_platform: linux/amd64
            platform: x86_64
          - build_platform: linux/arm64
            platform: aarch64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: libook
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        env:
          # VERSION: ${{ github.event.release.tag_name }}
          VERSION: v0.2.1
        run: |
          docker buildx create --use
          docker buildx build \
            --platform ${{ matrix.build_platform }} \
            --build-arg VERSION=${VERSION} \
            --build-arg PLATFORM=${{ matrix.platform }} \
            -t libook/net-ssr-${{ matrix.binary }}:${VERSION} \
            -t libook/net-ssr-${{ matrix.binary }}:latest \
            -f docker/Dockerfile.${{ matrix.binary }} \
            --push \
            .
